### PR TITLE
(WIP) Integer root fix

### PR DESCRIPTION
**Pull request by b-mehta**
Fix for issue #177.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Huge thanks for investigation, now it makes sense.

It is probably worth to change `otherwise` case below in a similar fashion.

Also, when `k >= 1024` even `n `shiftRInteger` (h# *# k#)` may appear larger than `2^1024` and thus be converted to `Infinity :: Double`. We can resort to a simpler approximation in this case:

```haskell
appKthRoot k@(I# k#) n
  | k >= 1024 = 1 `shiftLInteger` (integerLog2# n `quotInt#` k# +# 1#)
  | otherwise = ...
```

**Comment by b-mehta** [comment]
Perhaps I'm missing something, but would 
```haskell
1 `shiftLInteger` (integerLog2# n `quotInt#` k#)
```
not be a better approximation?

**Comment by b-mehta** [comment]
Also, do you have suggestions for further test cases that could be added to verify these?

**Comment by Bodigrim** [comment]
I would probably just copy-paste `Math.NumberTheory.Powers.GeneralTests.integerRootProperty` to focus on huge inputs. Something along these lines:

```haskell
integerRootHugeProperty :: Huge Natural -> Large Word -> Bool
integerRootHugeProperty (Huge n) (Large pow') = pow == 0 ||
  toInteger root ^ pow <= toInteger n && toInteger n < toInteger (root + 1) ^ pow
    where
      pow = pow' `mod` 2000
      root = integerRoot pow n
```

**Comment by b-mehta** [comment]
`Huge` inputs are already tested in `testIntegral2Property`, I think...

**Comment by Bodigrim** [comment]
Correct, but only for small powers, I believe.

**Comment by b-mehta** [comment]
Ah, I see!

**Comment by Bodigrim** [comment]
Nice, well done!

**Pull request merged**
